import { PartnerVenue } from '../types';

export const getTodayDateString = (offsetDays = 0): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_PARTNER_VENUES: PartnerVenue[] = [
  {
    id: 'venue-oasis-casa',
    name: 'مركب الواحة الرياضي لكرة القدم (Oasis Soccer Complex)',
    city: 'Casablanca',
    address: 'Boulevard de l\'Oasis, près de la gare Oasis, Casablanca',
    googleMapsUrl: 'https://maps.google.com/?q=Oasis+Sports+Club+Casablanca',
    phone: '+212 6 61 23 45 67',
    whatsapp: '212661234567',
    managerName: 'الحاج حسن الشرايبي',
    managerEmail: 'oasis.contact@gomatch.ma',
    formats: ['7v7', '5v5', '9v9'],
    turfType: 'synthetic_fifa',
    hourlyRateMAD: 550,
    pitchCount: 3,
    imageUrl: '/images/stadiums/floodlit_night_arena.jpg',
    amenities: ['parking', 'showers', 'night_lighting', 'cafeteria', 'bibs_balls', 'prayer_room'],
    openingTime: '09:00',
    closingTime: '01:30',
    isVerifiedPartner: true,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-03-01T12:00:00Z',
    slots: [
      {
        id: 'slot-oasis-1',
        venueId: 'venue-oasis-casa',
        pitchNumber: 'الملعب رقم 1 (عشب فيفا برو)',
        format: '7v7',
        date: getTodayDateString(0),
        startTime: '18:00',
        endTime: '19:30',
        priceTotal: 550,
        status: 'available',
        notes: 'إضاءة كاشفة عالية الجودة + كرات وقمصان مجانية',
        createdAt: '2026-03-01T08:00:00Z',
      },
      {
        id: 'slot-oasis-2',
        venueId: 'venue-oasis-casa',
        pitchNumber: 'الملعب رقم 2',
        format: '7v7',
        date: getTodayDateString(0),
        startTime: '19:30',
        endTime: '21:00',
        priceTotal: 550,
        status: 'booked',
        bookedByName: 'نادي الوداد هواة',
        bookedByPhone: '+212 6 00 11 22 33',
        createdAt: '2026-03-01T08:00:00Z',
      },
      {
        id: 'slot-oasis-3',
        venueId: 'venue-oasis-casa',
        pitchNumber: 'الملعب رقم 1',
        format: '7v7',
        date: getTodayDateString(0),
        startTime: '21:00',
        endTime: '22:30',
        priceTotal: 550,
        status: 'available',
        notes: 'الحصة الذهبية المسائية',
        createdAt: '2026-03-01T08:00:00Z',
      },
      {
        id: 'slot-oasis-4',
        venueId: 'venue-oasis-casa',
        pitchNumber: 'الملعب رقم 3 (صغير)',
        format: '5v5',
        date: getTodayDateString(1),
        startTime: '20:00',
        endTime: '21:30',
        priceTotal: 400,
        status: 'available',
        notes: 'مناسب لمباريات 5 ضد 5 السريعة',
        createdAt: '2026-03-01T08:00:00Z',
      },
    ],
  },
  {
    id: 'venue-agdal-rabat',
    name: 'المركب الرياضي أكدال (Complexe Agdal Foot)',
    city: 'Rabat',
    address: 'Avenue de France, Agdal, Rabat',
    googleMapsUrl: 'https://maps.google.com/?q=Agdal+Sports+Rabat',
    phone: '+212 6 62 88 99 00',
    whatsapp: '212662889900',
    managerName: 'الكابتن مهدي الفاسي',
    managerEmail: 'agdal.arena@gomatch.ma',
    formats: ['7v7', '6v6', '5v5'],
    turfType: 'synthetic_fifa',
    hourlyRateMAD: 500,
    pitchCount: 2,
    imageUrl: '/images/stadiums/premier_championship_pitch.jpg',
    amenities: ['parking', 'showers', 'night_lighting', 'bibs_balls', 'cafeteria'],
    openingTime: '10:00',
    closingTime: '01:00',
    isVerifiedPartner: true,
    createdAt: '2026-01-15T11:00:00Z',
    updatedAt: '2026-03-02T14:00:00Z',
    slots: [
      {
        id: 'slot-agdal-1',
        venueId: 'venue-agdal-rabat',
        pitchNumber: 'الملعب الرئيسي (Terrain A)',
        format: '7v7',
        date: getTodayDateString(0),
        startTime: '19:00',
        endTime: '20:30',
        priceTotal: 500,
        status: 'available',
        notes: 'مستودعات ملابس مجهزة ودش ساخن',
        createdAt: '2026-03-02T09:00:00Z',
      },
      {
        id: 'slot-agdal-2',
        venueId: 'venue-agdal-rabat',
        pitchNumber: 'الملعب الرئيسي (Terrain A)',
        format: '7v7',
        date: getTodayDateString(0),
        startTime: '20:30',
        endTime: '22:00',
        priceTotal: 500,
        status: 'available',
        notes: 'إمكانية توفير حكم رسمي عند الطلب',
        createdAt: '2026-03-02T09:00:00Z',
      },
      {
        id: 'slot-agdal-3',
        venueId: 'venue-agdal-rabat',
        pitchNumber: 'Terrain B',
        format: '5v5',
        date: getTodayDateString(1),
        startTime: '18:30',
        endTime: '20:00',
        priceTotal: 380,
        status: 'available',
        createdAt: '2026-03-02T09:00:00Z',
      },
    ],
  },
  {
    id: 'venue-marina-tanger',
    name: 'أكاديمية مارينا طنجة سيتي (Tangier Bay Arena)',
    city: 'Tanger',
    address: 'Boulevard Mohamed VI, Malabata, Tanger',
    googleMapsUrl: 'https://maps.google.com/?q=Malabata+Tangier',
    phone: '+212 6 63 44 55 66',
    whatsapp: '212663445566',
    managerName: 'الأستاذ رشيد الإدريسي',
    managerEmail: 'marina.tangier@gomatch.ma',
    formats: ['7v7', '8v8', '11v11'],
    turfType: 'synthetic_fifa',
    hourlyRateMAD: 600,
    pitchCount: 2,
    imageUrl: '/images/stadiums/coastal_stadium.jpg',
    amenities: ['parking', 'showers', 'night_lighting', 'cafeteria', 'bibs_balls', 'prayer_room'],
    openingTime: '08:00',
    closingTime: '02:00',
    isVerifiedPartner: true,
    createdAt: '2026-01-20T14:00:00Z',
    updatedAt: '2026-03-03T16:00:00Z',
    slots: [
      {
        id: 'slot-tanger-1',
        venueId: 'venue-marina-tanger',
        pitchNumber: 'ملعب البحر المتوسط (7v7)',
        format: '7v7',
        date: getTodayDateString(0),
        startTime: '20:00',
        endTime: '21:30',
        priceTotal: 600,
        status: 'available',
        notes: 'إطلالة بحرية رائعة وأرضية ممتازة',
        createdAt: '2026-03-03T10:00:00Z',
      },
      {
        id: 'slot-tanger-2',
        venueId: 'venue-marina-tanger',
        pitchNumber: 'ملعب البحر المتوسط (7v7)',
        format: '7v7',
        date: getTodayDateString(1),
        startTime: '21:30',
        endTime: '23:00',
        priceTotal: 600,
        status: 'available',
        createdAt: '2026-03-03T10:00:00Z',
      },
    ],
  },
  {
    id: 'venue-palmeraie-marrakech',
    name: 'أرينا النخيل للرياضة (Palmeraie Arena Club)',
    city: 'Marrakech',
    address: 'Circuit de la Palmeraie, Marrakech',
    googleMapsUrl: 'https://maps.google.com/?q=Palmeraie+Marrakech',
    phone: '+212 6 64 77 88 99',
    whatsapp: '212664778899',
    managerName: 'الكابتن طارق الوردي',
    managerEmail: 'palmeraie.kech@gomatch.ma',
    formats: ['5v5', '7v7'],
    turfType: 'indoor_hall',
    hourlyRateMAD: 450,
    pitchCount: 2,
    imageUrl: '/images/stadiums/grand_sunset_arena.jpg',
    amenities: ['parking', 'showers', 'night_lighting', 'cafeteria', 'bibs_balls', 'prayer_room'],
    openingTime: '09:00',
    closingTime: '01:00',
    isVerifiedPartner: true,
    createdAt: '2026-02-01T15:00:00Z',
    updatedAt: '2026-03-04T10:00:00Z',
    slots: [
      {
        id: 'slot-kech-1',
        venueId: 'venue-palmeraie-marrakech',
        pitchNumber: 'القاعة المغطاة فوتسال (Terrain Indoor)',
        format: '5v5',
        date: getTodayDateString(0),
        startTime: '19:00',
        endTime: '20:30',
        priceTotal: 450,
        status: 'available',
        notes: 'صالة مغطاة ومكيفة مناسبة جداً للطقس الدافئ',
        createdAt: '2026-03-04T11:00:00Z',
      },
      {
        id: 'slot-kech-2',
        venueId: 'venue-palmeraie-marrakech',
        pitchNumber: 'الملعب المفتوح (7v7)',
        format: '7v7',
        date: getTodayDateString(0),
        startTime: '21:00',
        endTime: '22:30',
        priceTotal: 480,
        status: 'available',
        createdAt: '2026-03-04T11:00:00Z',
      },
    ],
  },
];
