import { SoccerMatch, UserProfile, SUPER_ADMIN_EMAIL, AdminAnnouncement, DirectMessage, InAppNotification } from '../types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user_admin_main',
    email: 'moustafa325476@gmail.com',
    name: 'Mustapha Bouhbous',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+212 661-234567',
    city: 'Casablanca',
    isAdmin: true,
    status: 'approved',
    preferredPosition: 'MID',
    skillRating: 5.0,
    reliabilityScore: 100,
    matchesAttended: 52,
    noShowCount: 0,
    matchesPlayed: 52,
    mvpCount: 8,
    goalsCount: 24,
    badges: [
      { id: 'b1', key: 'reliable', title: 'Reliable Captain', description: '100% attendance rate', icon: '🛡️', unlockedAt: '2026-01-10' },
      { id: 'b2', key: 'mvp', title: 'Match MVP', description: 'Voted Best Player 8 times', icon: '🌟', unlockedAt: '2026-02-14' },
      { id: 'b3', key: 'ironman', title: 'Iron Man', description: '10 consecutive matches attended', icon: '⚡', unlockedAt: '2026-03-01' },
    ],
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    approvedAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'user_mustapha_alt',
    email: 'topreviewsamazon2025@gmail.com',
    name: 'Mustapha Bouhbous',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+212 661-234567',
    city: 'Casablanca',
    isAdmin: true,
    status: 'approved',
    preferredPosition: 'MID',
    skillRating: 5.0,
    reliabilityScore: 100,
    matchesAttended: 52,
    noShowCount: 0,
    matchesPlayed: 52,
    mvpCount: 8,
    goalsCount: 24,
    badges: [
      { id: 'b1', key: 'reliable', title: 'Reliable Captain', description: '100% attendance rate', icon: '🛡️', unlockedAt: '2026-01-10' },
      { id: 'b2', key: 'mvp', title: 'Match MVP', description: 'Voted Best Player 8 times', icon: '🌟', unlockedAt: '2026-02-14' },
      { id: 'b3', key: 'ironman', title: 'Iron Man', description: '10 consecutive matches attended', icon: '⚡', unlockedAt: '2026-03-01' },
    ],
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    approvedAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'user_mustapha',
    email: 'bouhbousmustapha@gmail.com',
    name: 'Mustapha Bouhbous',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+212 661-234567',
    city: 'Casablanca',
    isAdmin: true,
    status: 'approved',
    preferredPosition: 'MID',
    skillRating: 4.9,
    reliabilityScore: 99,
    matchesAttended: 48,
    noShowCount: 0,
    matchesPlayed: 48,
    mvpCount: 6,
    goalsCount: 19,
    badges: [
      { id: 'b1', key: 'reliable', title: 'Reliable Captain', description: '99% attendance rate', icon: '🛡️', unlockedAt: '2026-01-10' },
      { id: 'b2', key: 'mvp', title: 'Match MVP', description: 'Voted Best Player 6 times', icon: '🌟', unlockedAt: '2026-02-14' },
    ],
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    approvedAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'user_yassine',
    email: 'yassine.bounou@pitchmate.ma',
    name: 'Yassine Bounou',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+212 662-889900',
    city: 'Casablanca',
    isAdmin: false,
    status: 'approved',
    preferredPosition: 'GK',
    skillRating: 5.0,
    reliabilityScore: 100,
    matchesAttended: 38,
    noShowCount: 0,
    matchesPlayed: 38,
    mvpCount: 5,
    goalsCount: 0,
    badges: [
      { id: 'b4', key: 'glove', title: 'Golden Glove', description: 'Top rated Goalkeeper', icon: '🧤', unlockedAt: '2026-02-01' },
    ],
    createdAt: new Date(Date.now() - 75 * 86400000).toISOString(),
    approvedAt: new Date(Date.now() - 75 * 86400000).toISOString(),
  },
  {
    id: 'user_achraf',
    email: 'achraf.hakimi@pitchmate.ma',
    name: 'Achraf Hakimi',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+212 663-112233',
    city: 'Rabat',
    isAdmin: false,
    status: 'approved',
    preferredPosition: 'DEF',
    skillRating: 4.9,
    reliabilityScore: 98,
    matchesAttended: 34,
    noShowCount: 0,
    matchesPlayed: 34,
    mvpCount: 4,
    goalsCount: 12,
    badges: [
      { id: 'b3', key: 'speed', title: 'Pace Master', description: 'Top wing defender', icon: '⚡', unlockedAt: '2026-02-10' },
    ],
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    approvedAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'user_sofyan',
    email: 'sofyan.amrabat@pitchmate.ma',
    name: 'Sofyan Amrabat',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    phone: '+212 664-445566',
    city: 'Marrakech',
    isAdmin: false,
    status: 'approved',
    preferredPosition: 'MID',
    skillRating: 4.8,
    reliabilityScore: 97,
    matchesAttended: 29,
    noShowCount: 1,
    matchesPlayed: 29,
    mvpCount: 3,
    goalsCount: 8,
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    approvedAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'user_youssef',
    email: 'youssef.nesyri@pitchmate.ma',
    name: 'Youssef En-Nesyri',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    phone: '+212 665-778899',
    city: 'Fes',
    isAdmin: false,
    status: 'approved',
    preferredPosition: 'FWD',
    skillRating: 4.7,
    reliabilityScore: 96,
    matchesAttended: 26,
    noShowCount: 1,
    matchesPlayed: 26,
    mvpCount: 4,
    goalsCount: 22,
    badges: [
      { id: 'b5', key: 'sniper', title: 'Top Scorer', description: 'Over 20 goals scored', icon: '🎯', unlockedAt: '2026-03-01' },
    ],
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    approvedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
];

const now = new Date();

const tomorrowNight = new Date(now.getTime() + 24 * 60 * 60 * 1000);
tomorrowNight.setHours(20, 30, 0, 0);

const dayAfterDawn = new Date(now.getTime() + 48 * 60 * 60 * 1000);
dayAfterDawn.setHours(7, 0, 0, 0);

const weekendNight = new Date(now.getTime() + 72 * 60 * 60 * 1000);
weekendNight.setHours(19, 0, 0, 0);

export const INITIAL_MATCHES: SoccerMatch[] = [
  {
    id: 'match_01_casablanca_lights',
    title: 'Casablanca 7v7 Under The Floodlights',
    dateTime: tomorrowNight.toISOString(),
    durationMinutes: 90,
    location: {
      venueName: 'Oasis Soccer Club',
      address: 'Route de l’Oasis, Near Tramway Station',
      city: 'Casablanca',
      latitude: 33.5658,
      longitude: -7.6324,
      googleMapsUrl: 'https://maps.google.com/?q=33.5658,-7.6324',
      pitchNumber: 'Terrain 2 (Synthetic Turf)',
    },
    format: '7v7',
    maxPlayers: 14,
    pricePerPlayer: 50,
    currency: 'MAD',
    totalPitchCost: 700,
    paidPlayerIds: ['user_mustapha', 'user_yassine'],
    formationGreen: '7v7-2-3-1',
    formationBlue: '7v7-2-3-1',
    score: { green: 3, blue: 2 },
    goals: [
      { id: 'g1', minute: 15, team: 'green', scorerId: 'user_mustapha', scorerName: 'Mustapha Bouhbous' },
      { id: 'g2', minute: 28, team: 'blue', scorerId: 'user_youssef', scorerName: 'Youssef En-Nesyri' },
      { id: 'g3', minute: 44, team: 'green', scorerId: 'user_mustapha', scorerName: 'Mustapha Bouhbous' },
    ],
    notes: 'Match rental split is 50 MAD/player (Total 700 MAD). Bibs and official match balls provided. Payment via CIH Bank or Cash on pitch.',
    creatorId: 'user_mustapha',
    creatorName: 'Mustapha Bouhbous',
    creatorEmail: SUPER_ADMIN_EMAIL,
    roster: [
      {
        userId: 'user_mustapha',
        name: 'Mustapha Bouhbous',
        email: SUPER_ADMIN_EMAIL,
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        joinedAt: new Date(now.getTime() - 120000).toISOString(),
        team: 'green',
        position: 'MID',
        jerseyNumber: 10,
        isHost: true,
        reliabilityScore: 100,
        rating: 5.0,
        paymentStatus: 'paid',
        paymentMethod: 'cash',
      },
      {
        userId: 'user_yassine',
        name: 'Yassine Bounou',
        email: 'yassine.bounou@pitchmate.ma',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        joinedAt: new Date(now.getTime() - 100000).toISOString(),
        team: 'green',
        position: 'GK',
        jerseyNumber: 1,
        reliabilityScore: 100,
        rating: 5.0,
        paymentStatus: 'paid',
        paymentMethod: 'cih_bank',
      },
      {
        userId: 'user_achraf',
        name: 'Achraf Hakimi',
        email: 'achraf.hakimi@pitchmate.ma',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        joinedAt: new Date(now.getTime() - 80000).toISOString(),
        team: 'green',
        position: 'DEF',
        jerseyNumber: 2,
        reliabilityScore: 98,
        rating: 4.9,
        paymentStatus: 'pending',
      },
      {
        userId: 'user_sofyan',
        name: 'Sofyan Amrabat',
        email: 'sofyan.amrabat@pitchmate.ma',
        avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
        joinedAt: new Date(now.getTime() - 60000).toISOString(),
        team: 'blue',
        position: 'MID',
        jerseyNumber: 4,
        reliabilityScore: 97,
        rating: 4.8,
        paymentStatus: 'unpaid',
      },
      {
        userId: 'user_youssef',
        name: 'Youssef En-Nesyri',
        email: 'youssef.nesyri@pitchmate.ma',
        avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        joinedAt: new Date(now.getTime() - 40000).toISOString(),
        team: 'blue',
        position: 'FWD',
        jerseyNumber: 9,
        reliabilityScore: 96,
        rating: 4.7,
        paymentStatus: 'unpaid',
      },
    ],
    waitlist: [],
    isLocked: false,
    status: 'upcoming',
    createdAt: new Date(now.getTime() - 150000).toISOString(),
    updatedAt: new Date(now.getTime() - 20000).toISOString(),
  },
  {
    id: 'match_02_rabat_agdal',
    title: 'Rabat Agdal Weekend 6v6 Cup',
    dateTime: weekendNight.toISOString(),
    durationMinutes: 80,
    location: {
      venueName: 'Complexe Sportif Agdal',
      address: 'Avenue de France, Agdal',
      city: 'Rabat',
      latitude: 33.9982,
      longitude: -6.8489,
      googleMapsUrl: 'https://maps.google.com/?q=33.9982,-6.8489',
      pitchNumber: 'Terrain 1',
    },
    format: '6v6',
    maxPlayers: 12,
    pricePerPlayer: 45,
    currency: 'MAD',
    totalPitchCost: 540,
    paidPlayerIds: ['user_mustapha'],
    formationGreen: '6v6-2-2-1',
    formationBlue: '6v6-2-2-1',
    notes: 'Kickoff at 19:00 Morocco Time sharp! Please arrive 15 minutes before for warm-up.',
    creatorId: 'user_mustapha',
    creatorName: 'Mustapha Bouhbous',
    creatorEmail: SUPER_ADMIN_EMAIL,
    roster: [
      {
        userId: 'user_mustapha',
        name: 'Mustapha Bouhbous',
        email: SUPER_ADMIN_EMAIL,
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        joinedAt: new Date(now.getTime() - 90000).toISOString(),
        team: 'green',
        position: 'MID',
        jerseyNumber: 10,
        isHost: true,
        reliabilityScore: 100,
        rating: 5.0,
        paymentStatus: 'paid',
        paymentMethod: 'cash',
      },
      {
        userId: 'user_achraf',
        name: 'Achraf Hakimi',
        email: 'achraf.hakimi@pitchmate.ma',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        joinedAt: new Date(now.getTime() - 70000).toISOString(),
        team: 'blue',
        position: 'DEF',
        jerseyNumber: 2,
        reliabilityScore: 98,
        rating: 4.9,
        paymentStatus: 'pending',
      },
    ],
    waitlist: [],
    isLocked: false,
    status: 'upcoming',
    createdAt: new Date(now.getTime() - 100000).toISOString(),
    updatedAt: new Date(now.getTime() - 10000).toISOString(),
  },
];

export const POPULAR_PITCH_PRESETS = [
  {
    name: 'Stade Oasis Soccer Complex',
    address: 'Boulevard de l\'Oasis, Casablanca',
    city: 'Casablanca',
    latitude: 33.5592,
    longitude: -7.6321,
    notes: 'Premium 4G artificial turf with floodlights and parking',
  },
  {
    name: 'City Foot 5 Californie',
    address: 'Quartier Californie, Casablanca',
    city: 'Casablanca',
    latitude: 33.5389,
    longitude: -7.6015,
    notes: 'Five-a-side indoor and outdoor pitches with locker rooms',
  },
  {
    name: 'Complexe Sportif Hay Riad',
    address: 'Avenue Annakhil, Hay Riad, Rabat',
    city: 'Rabat',
    latitude: 33.9682,
    longitude: -6.8791,
    notes: 'Modern 7v7 and 11v11 pitches with high quality LED lighting',
  },
  {
    name: 'Palmerie Football Club Marrakech',
    address: 'Circuit de la Palmeraie, Marrakech',
    city: 'Marrakech',
    latitude: 31.6628,
    longitude: -7.9532,
    notes: 'Beautiful outdoor turf surrounded by palms, great clubhouse',
  },
  {
    name: 'Tangier Bay Sports Village',
    address: 'Route de Malabata, Tangier',
    city: 'Tangier',
    latitude: 35.7761,
    longitude: -5.7821,
    notes: 'Ocean-view synthetic pitches, 7v7 and 8v8 format',
  },
  {
    name: 'Agadir Marina Pitch Center',
    address: 'Boulevard 20 Août, Agadir',
    city: 'Agadir',
    latitude: 30.4215,
    longitude: -9.6052,
    notes: 'Coastal turf venue close to the marina',
  },
];

export const INITIAL_ANNOUNCEMENTS: AdminAnnouncement[] = [
  {
    id: 'ann_1',
    title: 'PitchMate Morocco League Guidelines & Dirham (MAD) Fees',
    message: 'Welcome to PitchMate Morocco! All matches are now scheduled in Morocco GMT+1 (Casablanca time) with transparent Dirham (MAD) fee tracking, live scoreboard, and MVP voting.',
    authorName: 'Mustapha Bouhbous (Super Admin)',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    type: 'info',
  },
];

export const INITIAL_DIRECT_MESSAGES: DirectMessage[] = [
  {
    id: 'dm_1',
    senderId: 'user_yassine',
    senderName: 'Yassine Bounou',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    receiverId: 'user_mustapha',
    text: 'Salam Captain Mustapha! I will bring the goalkeeper gloves and two official match balls for the Oasis match tomorrow.',
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    read: true,
  },
];

export const INITIAL_NOTIFICATIONS: InAppNotification[] = [
  {
    id: 'notif_1',
    userId: 'user_mustapha',
    title: 'Welcome to PitchMate Morocco',
    message: 'Your Super Admin portal is active with full Moroccan Dirham (MAD) fee splits and Casablanca GMT+1 scheduler.',
    type: 'system',
    createdAt: new Date().toISOString(),
    read: false,
  },
];
